<div class="row">
    <div class="jumbotron col-md-8">
        <h1>
            <?php echo 'ZfcRbac Application' ?>
        </h1>

        <p>
            <a class="btn btn-success btn-lg" href="https://github.com/jmleroux/zfc-rbac-application" target="_blank">
                <?php echo 'ZfcRbac Application on GitHub' ?> &raquo;
            </a>
        </p>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Your identity</h3>
            </div>
            <div class="panel-body">
                <p><?php echo $this->identityDetails() ?></p>
            </div>
        </div>
    </div>
</div>

<h3>Route guards - role based</h3>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Member only route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "member" role
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('member-only') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Admin only route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "admin" role
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('admin-only') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Admin or member route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "admin" or "member" role
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('admin-or-member') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Other only route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "other" role
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('other-only') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

<hr/>

<h3>Route guards - permission based</h3>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Update route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "update" permission
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('update-permission') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Delete route</h3>
            </div>
            <div class="panel-body">
                <p>
                    A route only for users with the "delete" permission
                </p>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('delete-permission') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

<h3>Route guards - permission based + Controller Guard - role based</h3>

<div class="row">
    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Read route</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li>The route is only accessible for users with the "read" permission.</li>
                    <li>The controller is only accessible for users with the "member" role.</li>
                </ul>

                <p>
                    <a class="btn btn-success pull-right"
                       href="<?php echo $this->url('read-permission') ?>">
                        Test &raquo;
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
